[project]
name = "newbot"
version = "2.0.0-rc.1"
description = "a bot made by JavaScript(frontend) and python(backend)"
requires-python = ">=3.12.12"
authors = [
  { name = "heyu1145", email = "216254631+heyu1145@users.noreply.github.com" },
]
readme = "README.md"
license = "MIT"

dependencies = [
  "discord-py>=2.7.0",
  "fastapi>=0.125.0",
  "python-dotenv>=1.1.0",
  "psutil>=7.0.0",
  "aiohttp>=3.13.0",
  "uvicorn>=0.34.0",
  "packaging>=26.0",
]


[dependency-groups]
dev = [
  "mypy>=1.19.0",
  "pyright>=1.1.0",
  "pytest>=9.0.2",
  "pytest-asyncio>=1.3.0",
  "pytest-cov>=7.0.0",
]


[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
  "**/tests/**/*",
  "**/.venv/**/*",
  "**/.env",
  "**/.venv",
  "**/__init__.py",
]
