name: CI

on:
  push:
    branches: [ main, feature-* ]
  pull_request:
    branches: [ main ]

jobs:
  static_test:
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.12, 3.13, 3.14 ]
      fail-fast: false

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install dependencies
        run: uv sync --frozen --extra dev

      - name: run pyright test
        run: uv run pyright .

      - name: run mypy test
        id: mypy
        run: uv run mypy . --exclude-gitignore --disable-error-code import-untyped --linecount-report .

      - name: upload mypy result
        uses: actions/upload-artifact@v4
        with:
          name: linecount-report-${{ matrix.os-version }}-${{ matrix.python-version }}
          path: linecount.txt

      - name: run pytest test
        run: uv run pytest . -q --cov --cov-fail-under 80 --cov-report=markdown --cov-report=term-missing

      - name: upload pytest result
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os-version }}-${{ matrix.python-version }}
          path: coverage.md

  merge_result:
    runs-on: ubuntu-latest
    needs: static_test
    if: success()

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: all-reports

      - name: make new dir
        run: mkdir report-zips

      - name: pack the result (mypy)
        run: zip -r report-zips/mypy-reports.zip all-reports/linecount-*

      - name: pack the result (pytest)
        run: zip -r report-zips/coverage-reports.zip all-reports/coverage-*

      - name: upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: report-zips/
